### ISSUE TITLE
ConfigType parameter missing in latest version

### ISSUE THREAD

**Issue by sandeepc24** [demetrixbio/FSharp.Data.Npgsql#104]
I have been using ConfigType = ConfigType.Environment to read connection string from environment, now it is not there, how do I read connection string from environment?

**Comment by sandeep-eroad** [comment]
It looks like @kerams removed the config type here - https://github.com/demetrixbio/FSharp.Data.Npgsql/commit/e0962f6d9aff1881e762a9a7be2fb7d6b4c50247?diff=split

Not sure why, is there a reason behind this @kerams ?

**Comment by sandeep-eroad** [comment]
Without ConfigType we will not be able to upgrade to latest version as all our infrastructure relies on setting different connection string for different environments.

**Comment by kerams** [comment]
I removed ConfigType in my diverged fork of this repo because I had no use for it. All the changes were later merged in back here.

**Comment by piaste** [comment]
> Without ConfigType we will not be able to upgrade to latest version as all our infrastructure relies on setting different connection string for different environments.

We use [FSharp.Data.LiteralProviders](https://github.com/Tarmil/FSharp.Data.LiteralProviders) to read TP parameters from the environment, it works really well. You can also read from text files if you want.

**Comment by sandeepc24** [comment]
Thanks, that works like a charm!
