### ISSUE TITLE
Retrieve tables meta info without InformationSchema

### ISSUE THREAD

**Issue by dmitry-a-morozov** [demetrixbio/FSharp.Data.Npgsql#11]

**Comment by kerams** [comment]
This appears to be the case now https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/master/src/DesignTime/InformationSchema.fs#L411

**Comment by melanore** [comment]
As @kerams pointed out, this issue was fixed in scope of https://github.com/demetrixbio/FSharp.Data.Npgsql/pull/40.
