### ISSUE TITLE
Runtime assembly load error 

### ISSUE THREAD

**Issue by sandeepc24** [demetrixbio/FSharp.Data.Npgsql#13]
With dotnet core I do not get any errors while coding in VS Code but the build fails with following error

`error FS3033: The type provider 'FSharp.Data.Npgsql.NpgsqlProviders' reported an error: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. `

**Comment by dmitry-a-morozov** [comment]
I got this error too recently. 
Make sure you have recent .NET Core 2.1.4 SDK installed. 
https://www.microsoft.com/net/download/

**Comment by sandeepc24** [comment]
I have 2.1.4 SDK Installed, and that is the only version I have.

**Comment by dmitry-a-morozov** [comment]
did you try to run `dotnet restore` first?

**Comment by sandeepc24** [comment]
yes I did, I am using Paket, should that make any difference

**Comment by dmitry-a-morozov** [comment]
https://github.com/Microsoft/visualfsharp/issues/3303#issue-240393680
Do you have this fix applied to you project file?

**Comment by sandeepc24** [comment]
Thanks a lot, that fixed it.

**Comment by dmitry-a-morozov** [comment]
Great !
Docs mention it's here https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/master/README.md#setup
