### ISSUE TITLE
Update statement do not accept Option 

### ISSUE THREAD

**Issue by sandeepc24** [demetrixbio/FSharp.Data.Npgsql#14]
With `select` command columns which can be nulled are returned as Option but when doing `update` it is not possible to set those as Option types.

**Comment by dmitry-a-morozov** [comment]
By default all parameters are mandatory by design. 
Set `AllParametersOptional` in the type provider input to alter this behavior. 
https://github.com/demetrixbio/FSharp.Data.Npgsql#optional-input-parameters

**Comment by dmitry-a-morozov** [comment]
Also consider to use `ResultType.DataTable` to send updates to a database.
https://github.com/demetrixbio/FSharp.Data.Npgsql#data-modifications

**Comment by sandeepc24** [comment]
Thanks for pointing to those links. I have following situation 
```
match dateValue with
| Some date -> // Set column to date
| None -> // Set column to null
```

How do you recommend to do this?

**Comment by sandeepc24** [comment]
I am getting error
```
The type provider 'FSharp.Data.Npgsql.NpgsqlProviders' reported an error: Unable to cast object of type 'System.Int32' to type 'System.String'
```
in my command

```
        use con = openConnection()
        use trn = con.BeginTransaction()
        use selectCmd =
            new NpgsqlCommand<"
                    select
                        description
                        from jobs
                    where id = @JobId", ResultType.DataTable>(con, trn)
```
Id in my table is of type uuid.

**Comment by sandeepc24** [comment]
The issue I found with using DataTable is that 
```
use cmd = new NpgsqlCommand<" 
            UPDATE public.customer 
            SET activebool = false 
            WHERE email = @email 
                AND activebool
    ", dvdRental, SingleRow = true>(dvdRental)
```
I can't assign connection string read from ConfigurationBuilder

```
let dvdRental = lazy ConfigurationBuilder().AddJsonFile(config).Build().GetConnectionString(connectionStringName)
```

**Comment by dmitry-a-morozov** [comment]
Use `dvdRental.Value`

**Comment by sandeepc24** [comment]
I tried that and I get error `This is not a valid constant expression or custom attribute value`

**Comment by dmitry-a-morozov** [comment]
Sorry about confusion. 
Design time connection string has to be literal. 
Also it can be read from external configuration
https://github.com/demetrixbio/FSharp.Data.Npgsql#configuration
