### ISSUE TITLE
ProvidedTypes.fsi and ProvidedTypes.fs missing

### ISSUE THREAD

**Issue by sandeepc24** [demetrixbio/FSharp.Data.Npgsql#18]
I am trying to rebuild this project and files `ProvidedTypes.fsi`, `ProvidedTypes.fs` are missing from the repository which causes the DesignTime build to fail.

**Comment by dmitry-a-morozov** [comment]
FSharp.TypeProviders.SDK and npgsql are git submodules
To clone use
`git clone --recursive https://github.com/demetrixbio/FSharp.Data.Npgsql.git`
