### ISSUE TITLE
How to use different appsettings.json

### ISSUE THREAD

**Issue by sandeepc24** [demetrixbio/FSharp.Data.Npgsql#19]
I want to use different database for my test project and I am not sure how to point the type provider to different appsettings in my test project.

I have my config defined as
```
[<Literal>]
let config = __SOURCE_DIRECTORY__ + "/" + "appsettings.json"
```

This works fine in my web api project but in test project it is pointing to the web api dir and not picking the `appsettings.json` in my test project.

Is there a way to do what I want?

**Comment by dmitry-a-morozov** [comment]
Does it break at run-time or design time?

**Comment by sandeepc24** [comment]
Is this question for the other issue?

**Comment by dmitry-a-morozov** [comment]
The type provider uses `appsettings.json` like files only at design time. 
Make sure at build time you copy `appsettings.json` to output folder to make it works at run-time. 
Web projects do it by default that why it works for you.
