### ISSUE TITLE
Update to use the latest TP SDK

### ISSUE THREAD

**Issue by purkhusid** [demetrixbio/FSharp.Data.Npgsql#21]
Are there any plans to update this TP to use the latest TP SDK like they did with FSharp.Data? This would make it work on .Net Core without using the workaround that is mentioned int the readme.

**Comment by dmitry-a-morozov** [comment]
Fixed in 
https://www.nuget.org/packages/FSharp.Data.Npgsql/0.1.33-beta

Thanks for opening the issue.
