### ISSUE TITLE
System.Runtime error with 0.1.41.beta

### ISSUE THREAD

**Issue by sandeepc24** [demetrixbio/FSharp.Data.Npgsql#25]
I am getting following error after updating to 0.1.41.deta in VSCode IDE

```
The type provider 'FSharp.Data.Npgsql.NpgsqlProviders' reported an error: Could not load file or 
assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one 
of its dependencies. The system cannot find the file specified.
```

If I open the solution in VS2017 I don't get this error.

**Comment by dmitry-a-morozov** [comment]
Does 0.1.40-beta still work for you?
Did you recently upgrade to VS 15.8?

**Comment by sandeepc24** [comment]
I am using 0.1.41-beta, it is working fine.

Yes I upgraded to Vs 15.8.

**Comment by dmitry-a-morozov** [comment]
> I am using 0.1.41-beta, it is working fine.

Great. Can I close the issue?

**Comment by sandeepc24** [comment]
Yes, please.
