### ISSUE TITLE
Typed multiple result sets

### ISSUE THREAD

**Issue by kerams** [demetrixbio/FSharp.Data.Npgsql#39]
Plain Npgsql is able to return multiple result sets, which can be read using `NpgsqlDataReader`:
```fsharp
let con = new Npgsql.NpgsqlConnection (cs)
con.Open ()
let cmd = con.CreateCommand ()
cmd.CommandText <- "select * from actor limit 1; select * from address limit 1;"
let reader = cmd.ExecuteReader ()

while (reader.Read ()) do
    () // actors

reader.NextResult () |> ignore

while (reader.Read ()) do
    () // addresses
```

On the other hand,
```fsharp
let res = DvdRental.CreateCommand<"select * from actor limit 1; select * from address limit 1;">(cs).Execute ()
```

only produces a list of actors. I wonder if both actors and addresses could be exposed in a type-safe fashion.

**Comment by melanore** [comment]
This is doable, but will require some heavy changes to the ``ISqlCommand`` and quotations implementations. Current behavior is inline with FSharp.Data.SqlClient type provider - https://github.com/fsprojects/FSharp.Data.SqlClient/issues/331. 
Npgsql library does provide row description message per each result set, so this could work. However implementation will go too far away from original provider.
How critical is this for your use case?

**Comment by kerams** [comment]
It isn't anything I _need_, frankly. Since one can always fall back to Npgsql (`ResultType.DataReader` with the TP actually does not work, because only the first result set is populated), not having this is probably no biggie. I just thought it would be a shame not to make use of the type information if it's available upstream :).
