### ISSUE TITLE
Support for JSONB

### ISSUE THREAD

**Issue by sandeep-eroad** [demetrixbio/FSharp.Data.Npgsql#41]
I cannot use a table with JSONB and Composite type columns, are there plans to support these types?

**Comment by kerams** [comment]
Can you provide some repro for the jsonb case? It appears to be working for me.

![Untitled](https://user-images.githubusercontent.com/5063478/59090331-c89f3280-890c-11e9-89c3-10f5c98f28b8.png)

**Comment by kerams** [comment]
And I can select columns with composite types too. You'll get an ExpandoObject, but you can get data out of it dynamically.

**Comment by sandeep-eroad** [comment]
Try 
```
use tbl = new D.``public``.a()
tbl.AddRow()
```

**Comment by melanore** [comment]
jsonb/json DbParameter support added in https://github.com/demetrixbio/FSharp.Data.Npgsql/pull/48.
Please update to 0.1.48 version.
