### ISSUE TITLE
Specifying sort order using param

### ISSUE THREAD

**Issue by sandeep-eroad** [demetrixbio/FSharp.Data.Npgsql#43]
Is it possible to specify sort order using params? I would like to change the sort order of the query based on some flags and I tried using params but it did not work, not sure if there is something extra I need to do to make it work.

**Comment by sandeep-eroad** [comment]
@dmitry-a-morozov - are you still working on this project?

**Comment by daz10000** [comment]
Hey sorry for slow replies, just quite busy.   We encountered a similar kind of issue doing query building where you want very flexible SQL based on query inputs (more complicated than your example) and ended up concluding in our case it was beyond what we could reasonably expect from a type provider. In our case the parameters were polymorphic, so it effectively didn't have a fixed type signature.   Changing sort order is a baby version of that - you're not changing the output but are using input to make SQL polymorphic (you want to change order by asc|desc right?).   Not sure if that would even work at the ADO.Net level as a parameter.

**Comment by sandeep-eroad** [comment]
Thanks for the reply.

You are correct it doesn't even work with ADO.NET, so we ended up using Dapper with custom sql per sort order.

**Comment by daz10000** [comment]
Yeah - once you start building a general query engine you need to fully control SQL generation and can end up with polymorphic return types, so something like dapper / dynamic SQL generation is the way to go.
