### ISSUE TITLE
Add support for `in clause`

### ISSUE THREAD

**Issue by sandeep-eroad** [demetrixbio/FSharp.Data.Npgsql#45]
Is it possible to add support for `in clause` so that following queries can be executed

```
select * from some_table where some_column in (@ColumnValues)
```

**Comment by kerams** [comment]
`select * from some_table where some_column = any(@ColumnValues)`

**Comment by daz10000** [comment]
I guess first question is whether ado.net supports it?  If the underlying driver can somit, should be possible with the type provider

Darren

**Comment by sandeep-eroad** [comment]
@kerams - `=any` works. Thanks, will close this ticket.
