### ISSUE TITLE
Unsupported Datatype

### ISSUE THREAD

**Issue by NatElkins** [demetrixbio/FSharp.Data.Npgsql#46]
I was trying this library out, and I'm getting the following error:

<img width="753" alt="image" src="https://user-images.githubusercontent.com/1795462/65615538-849d6f80-df87-11e9-8c60-f1b5d6a8250f.png">

The same occurs when trying to use `NpgsqlConnection<"...">`.

Any ideas on how I can troubleshoot this?

Thanks!

**Comment by daz10000** [comment]
Could you provide more context - table definition,  maybe more complete code.  That should work (based on seeing just that line)

Von meinem iPhone gesendet

**Comment by NatElkins** [comment]
Okay, did a bit of investigation.  Might have something to do with a materialized view.

Here's a materialized view I've got:
<img width="275" alt="image" src="https://user-images.githubusercontent.com/1795462/65618042-a862b480-df8b-11e9-86df-b3dc3c7b61dd.png">

When I run this query from the code:

```sql
SELECT
    ns.OID AS schema_oid,
    ns.nspname AS schema_name,
    attr.attrelid AS table_oid,
    cls.relname AS table_name,
    pg_catalog.obj_description(attr.attrelid) AS table_description,
    attr.attnum AS col_number,
    attr.attname AS col_name,
    col.udt_name AS col_udt_name,
    col.data_type AS col_data_type,
    attr.attnotnull AS col_not_null,
    col.character_maximum_length AS col_max_length,
    CASE WHEN col.is_updatable = 'YES' THEN true ELSE false END AS col_is_updatable,
    CASE WHEN col.is_identity = 'YES' THEN true else false END AS col_is_identity,
    CASE WHEN attr.atthasdef THEN (SELECT pg_get_expr(adbin, cls.oid) FROM pg_attrdef WHERE adrelid = cls.oid AND adnum = attr.attnum) ELSE NULL END AS col_default,
    pg_catalog.col_description(attr.attrelid, attr.attnum) AS col_description,
    typ.oid AS col_typoid,
    EXISTS (
            SELECT * FROM pg_index
            WHERE pg_index.indrelid = cls.oid AND
                pg_index.indisprimary AND
                    attnum = ANY (indkey)
        ) AS col_part_of_primary_key
FROM pg_class AS cls
         INNER JOIN pg_namespace AS ns ON ns.oid = cls.relnamespace
         LEFT JOIN pg_attribute AS attr ON attr.attrelid = cls.oid AND attr.atttypid <> 0 AND attr.attnum > 0 AND NOT attr.attisdropped
         LEFT JOIN pg_type AS typ ON typ.oid = attr.atttypid
         LEFT JOIN information_schema.columns AS col ON col.table_schema = ns.nspname AND
                                                        col.table_name = relname AND
                                                        col.column_name = attname
WHERE
        cls.relkind IN ('r', 'v', 'm') AND
        ns.nspname !~ '^pg_' AND
        ns.nspname <> 'information_schema'
ORDER BY nspname, relname;
```

I see this in the results:

<img width="724" alt="image" src="https://user-images.githubusercontent.com/1795462/65618200-e233bb00-df8b-11e9-9fa7-c2da0164190f.png">

(take my word for it that those results correspond to the previously screenshotted materialized view)

Then take a look at this code: https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/e5b57610a7ac763aaf8f790988d9d85e2d3d822a/src/DesignTime/InformationSchema.fs#L438-L439

And follow it through to here: https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/e5b57610a7ac763aaf8f790988d9d85e2d3d822a/src/DesignTime/InformationSchema.fs#L94

Looks like it would fail there.  Think that could be it?

**Comment by NatElkins** [comment]
Just swinging back around to this because I was messing around a bit more.

That query I posted above, that gets all the columns and types.  If you add `typ.typname` as another column on the end, it gives you the same column datatype information you're looking for (except it works for materialized views too).

You could coalesce between `col_data_type` and that, although you'd have to do a little bit of messing around since it'll be `_datatype` if it's an array.  And if you have a materialized view of a custom data type, I don't know how you'd know since the data name will be null (I'm sure there's a way to figure it out, I just don't know Postgres well enough to know how).

Anyway, in the short term, maybe don't not worry about user defined types and just have the type name coalesce between `col.data_type` and `typ.typname`?  And do a little bit of extra logic to handle when it's an array.

I'd take a crack at it myself but I have no idea how to debug type providers.

**Comment by NatElkins** [comment]
Also maybe instead of failing with an unsupported data type just cast it as `obj`, same as when it's a user defined type that's not an enum.

**Comment by kerams** [comment]
@NatElkins Could you provide me with a create script for the problematic schema and what command you're trying to use?

**Comment by NatElkins** [comment]
Let me know if you still need anything from me.  Like I said in the previous comment, I feel like the solution involves looking at `typ.typname` to the schema query and getting the type information from there.

**Comment by kerams** [comment]
You're right about `typname` and identifying arrays by checking for the underscore. I just don't know how to tell if a type is user-define just by looking at pg_type.

**Comment by NatElkins** [comment]
Might just want to punt on that for now, user-defined types are relatively rare I think.
