### ISSUE TITLE
Suggestion: Add a static parameter specifying which methods should be generated

### ISSUE THREAD

**Issue by kerams** [demetrixbio/FSharp.Data.Npgsql#62]
I think it would be very rare for someone to use both `Execute` and `AsyncExecute`, so half the methods pretty much never see any action, yet their generation takes a toll (probably not a huge one though) on the design-time experience.

Therefore I propose we add a flags enum parameter to both `NpgsqlCommand` and `NpgsqlConnection` that would allow the user to choose which combination of methods they need. It would also come in handy should Task returning methods ever be supported.

**Comment by Swoorup** [comment]
Agree with this, it has always been one or the other. Will the generated methods have the same name?

**Comment by kerams** [comment]
I'd be against it. If nothing else, the names should at least stay consistent.
