### ISSUE TITLE
Update LegacyPostgis to NetTopologySuite

### ISSUE THREAD

**Issue by Swoorup** [demetrixbio/FSharp.Data.Npgsql#75]
I think we should upgrade Npgsql.LegacyPostgis to NetTopologySuite. Any reasons for using the old package?

**Comment by Swoorup** [comment]
@melanore Can we have a new nuget release. Would like to use this straightaway if you don't mind :smile:

**Comment by melanore** [comment]
0.2.8 released. Thanks for the MRs :)

**Comment by Swoorup** [comment]
MRs?

**Comment by daz10000** [comment]
PRs :) but you’re almost family now so it feels more like a merge 

Von meinem iPhone gesendet
