### ISSUE TITLE
netcoreapp2.1 in nuspec?

### ISSUE THREAD

**Issue by cartermp** [demetrixbio/FSharp.Data.Npgsql#78]
Hey folks,

We [regressed the F# compiler](https://github.com/dotnet/fsharp/blob/2a0b218095eaaa41f440ff4bcf50257a085190c0/src/utils/CompilerLocationUtils.fs#L259-L266) resulting in a regression where FSharp.Data.Npgsql fails to build here: https://github.com/dotnet/fsharp/issues/8832

We'll be adding back in assembly probing for `netcoreapp2.0`, which was removed because .NET Core 2.0 has been long unsupported.

The fix will align with the VS 16.6 release, but in the interim, if you change the TFM here to a supported runtime (such as `netcoreapp3.1`), then it should work:

https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/master/src/Runtime/FSharp.Data.Npgsql.nuspec#L25

**Comment by daz10000** [comment]
Can’t see any problems for us updating that. We generally like to stay pretty current.  Would that break for anyone out there ?

Darren

**Comment by cartermp** [comment]
My guess is likely not. .NET Core 2.0 went out of support in October of 2018, so I doubt folks are using it by now.

**Comment by cartermp** [comment]
Additionally, since all supported .NET Core runtimes implement .NET Standard 2.0, the `netstandard2.0` binary will always work for them.

**Comment by melanore** [comment]
Switched to .net standard in https://github.com/demetrixbio/FSharp.Data.Npgsql/pull/80. Thanks for help!

**Comment by cartermp** [comment]
Thanks!
