### ISSUE TITLE
Use paket for builds and remove net framework dependency

### ISSUE THREAD

**Issue by Swoorup** [demetrixbio/FSharp.Data.Npgsql#79]
For future builds can we remove net framework as a dependency? It seems like a lot of pain to get it working on mac and linux.

**Comment by melanore** [comment]
Type provider was migrated to netstandard2.0 without any net461 dependencies. It works smoothly on Windows/Unix using 3.1.201 SDK.  
As for paket, - we plan on migrating at some point in future. As usually, thanks for feedback. MRs are welcome.

**Comment by Swoorup** [comment]
I have a branch on which i have migrated tests and the actual solution to paket. Let me know if you'd like a PR. 

Do you why tests are testing an old package? 
https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/master/tests/SampleApp/SampleApp.fsproj#L17

**Comment by kerams** [comment]
That's just a sample app that's not used in integration testing.

**Comment by daz10000** [comment]
Happy to look at a PR.  Tests are unit tests in tests folder. 


Am 04.04.2020 um 2:34 AM schrieb Swoorup Joshi <notifications@github.com>:

**Comment by Swoorup** [comment]
Sure, I'll create it once I clean it up a bit.
